### ISSUE TITLE
Youtube preview thumbnails/links in Previous Videos menu broken

### ISSUE THREAD

**Issue by kitsandkats** [drewww/unhangout#402]
![screen shot 2015-05-05 at 3 16 09 pm](https://cloud.githubusercontent.com/assets/6548760/7480875/d697b294-f339-11e4-90b7-25ead5bb0242.png)

**Comment by thehunmonkgroup** [comment]
hm, looks ok on my development install, latest code on master branch:

![youtube-previews](https://cloud.githubusercontent.com/assets/43772/7493345/9c82846c-f3c5-11e4-8e60-a994868d93b2.png)

**Comment by kitsandkats** [comment]
seems like this resolved itself

**Comment by thehunmonkgroup** [comment]
i'm noticing this now both on my dev and production site, even with vids i loaded previously. highly suspect it's an intermittent youtube issue...
